### ISSUE TITLE
Design to-fix's

### ISSUE THREAD

**Issue by cherylhjli** [mondayrain/type-mixer#2]
Results page:
- "Congratulations, you've made a successful pairing!" - proper typeface doesn't show up, currently shows up as default serif
- Paragraph under the "congratulations..!" headings is slightly wider than the below paragraphs & horizontal line - they need to be the same width
- "try again" button is white, not the darker grey one
- Titles of typefaces need to be capitalized
- graphics of typefaces need to be centered

**Comment by mondayrain** [comment]
Making this into a bunch of different issues!
See
#3 
#4
#5
#6
